### ISSUE TITLE
[Meta] Create email message templates surrounding pd logistics

### ISSUE THREAD

**Issue by er1c456** [bootstrapworld/data-management#89]
- [ ] Create/post Statement of intention for Facilitators to receive email ahead of time
- why are you attending this training
- where do you see it fitting in to your professional work

[mailers folder](https://drive.google.com/drive/folders/10CbgI8Tp-u74lbIC9zoEJ0S6EaWJGU1T?usp=drive_link)

- [x] welcome email https://github.com/bootstrapworld/teacher-training-and-support/issues/25
- [x] Optional: (“looking forward to seeing you - here's a way to help you get your feet wet”) https://github.com/bootstrapworld/teacher-training-and-support/issues/25
- [x] workshop logistics
- [ ] facilitator thank you template
- [ ] invitation to coaching
- [x] bootstrapworld/teacher-training-and-support#18

**Comment by joystraub** [comment]
Link to sample pre-PD workshop from summer 2023: [https://docs.google.com/document/d/1IQQMkWnMcI_KM84KL9pJhrWgE6nyQN9PaOpregS1q4Y/edit?usp=sharing](url)
